Removed the keyboard input element from the template.
open-craft/xblock-skytap pull request #11
Opened 2018-06-11 12:02 UTC by afzaledx

2018-06-14 21:08 UTC, afzaledx commented
@itsjeyd, since I was not able to get a correct response from the boomi endpoint, I am not sure if removing the keyboard_layout parameter would be OK or not. the last commit adds back the keyboard layout parameter with a 'us' keyboard layout sent to the endpoint.

2018-06-15 07:27 UTC, itsjeyd requested changes
@afzaledx This LGTM, there's just one more method that you'll need to remove (see review comment). I already checked that the block loads correctly with these changes applied, and no longer shows the menu for selecting a keyboard layout.

The other thing that's left to figure out is whether we need to send a default value for `keyboard_layout`. I posted an update on the ticket about the `XBLOCK_SETTINGS` that should allow you to do the necessary testing without running into the error that you mentioned [here](https://tasks.opencraft.com/browse/OC-4621?focusedCommentId=75311&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-75311).

2018-06-15 07:27 UTC, itsjeyd commented on tests/integration/test_skytap.py
> -            self.assert_selected_option(menu, "us", "English (US)")
@afzaledx `assert_selected_option` is no longer used after this change, could you please remove it?

2018-06-18 07:59 UTC, itsjeyd approved these changes
@afzaledx Thanks for the updates! This is good to squash and merge :+1:

- [x] I tested this as described in https://github.com/open-craft/xblock-skytap/pull/11#pullrequestreview-129058649. Also, we [confirmed](https://tasks.opencraft.com/browse/OC-4621?focusedCommentId=75384&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-75384) that the Boomi endpoint returns a valid JSON response with and without the `"keyboard_layout"` key, and Rowan [said](https://trello.com/c/QqjFQiAC/179-remove-keyboard-field-from-skytap-xblock-oc-2135#comment-5b23c97b22c7bbabd6e1e242) that if we see any issues in production, Cloudera can follow internally and
    > remove the parts of the Boomi process that deal with the keyboard mapping.
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] ~~Includes documentation~~ N/A

2018-06-18 10:01 UTC, merged