WIP: Request sharing portal link from Boomi
open-craft/xblock-skytap pull request #3
Opened 2017-04-07 16:06 UTC by itsjeyd

cf. [OC-2505](https://tasks.opencraft.com/browse/OC-2505)

2017-04-10 22:46 UTC, bdero commented
@itsjeyd Fantastic! Thanks for working on this ahead of time. I'm going to take over this PR and implement the rest since I'm assigned to [OC-2505](https://tasks.opencraft.com/browse/OC-2505).

It looks like this is the only work remaining:
* Requesting a link to the sharing portal that is associated with the learner’s Skytap environment from Boomi, passing along preferred keyboard layout, e-mail address, course name, course run.
    * **On success**: Open the link to the sharing portal that belongs to the learner’s Skytap environment in a new window (or tab).
    * **On error**: Display an appropriate error message below the form.
Collaborating with Brian Hausmann for end-to-end tests.

2017-04-14 19:14 UTC, bdero commented
@haikuginger This PR is ready for review, although not every aspect is verifiable currently, as the live Cloudera Boomi endpoint isn't complete to the agreed specifications yet.

This PR has a good chunk of code in it, but the majority of it is for tests and grabbing settings for the XBlock. The meat and potatoes of this PR is from [this line](https://github.com/open-craft/xblock-skytap/pull/3/files#diff-d678185f8516d1615cae6845ef7d51d4R227) onwards.

At the time of writing, all of the following testing instructions should be valid and working. I tried to write them to be quick to follow and unambiguous. Let me know if you run into any issues during testing!

## Testing instructions

1. Install this version of the XBlock into a Devstack:
   ```
   pip install -e git+https://github.com/open-craft/xblock-skytap.git@request-link#egg=xblock-skytap==request-link
   ```
1. In Studio, add the Skytap XBlock to a course in studio by navigating to `Settings > Advanced Settings` and changing the "Advanced Module List" to the following:
   ```json
   [
       "skytap",
   ]
   ```
1. Make sure that `XBLOCK_SETTINGS` is currently an empty map in `lms.env.json`.
1. Create a fresh unit in the course and instantiate a new usage of the Skytap XBlock by selecting "Advanced > Skytap XBlock.
1. Now **Publish** the changes.
1. Click **View Live Version** to view the published unit in the LMS.
1. Click the **Launch** button on the Skytap XBlock's interface.
1. Observe that an error message displays *"Error: The Skytap XBlock is improperly configured."*
   ![Error screenshot](https://i.imgur.com/Ik5ZorC.png)
1. Change the `XBLOCK_SETTINGS` for `skytap` to use some fake data:
   ```json
   "XBLOCK_SETTINGS": {
       "skytap": {
           "boomi_configuration": {
               "base_url": "https://connect.boomi.example.com",
               "endpoint": "/ws/simple/createVm",
               "username": "foo",
               "token": "b8eaadd78-4ebd-4404-a261-690c8151e556"
           }
       }
   },
   ```
1. Restart the LMS and click the *Launch* button again. Observe that this time the error says "Error: An unknown error occurred while launching.". Check the LMS console and verify that a `ConnectionError` stacktrace has been logged.
1. Replace the fake `XBLOCK_SETTINGS` data with some "known working" data (see my comment on [OC-2505](https://tasks.opencraft.com/browse/OC-2505) for an example of known working data).
1. Restart the LMS and click the *Launch* button once more. Notice the button goes gray for quite a while. Be patient here, the Boomi endpoint sometimes takes over a minute to respond.
1. At the time of writing, there will be another error: *"Error: The Skytap launch service returned a malformed response."*. This happens because the Boomi endpoint is not yet finished on Cloudera's side; it currently directly returns the URL to the sharing portal, but the Skytap XBlock has been programmed to accept a JSON response containing a `SkytapURL` field. To verify that the response from Boomi was malformed, check the LMS console to make sure there was a `JSONDecodeError` stacktrace logged.

2017-04-17 14:07 UTC, haikuginger requested changes
A couple nits, and one change request - we need to tag user-visible strings for i18n. I tested the behavior, and it looks good, so once you add i18n, then I can give a 👍.

2017-04-17 14:07 UTC, haikuginger commented on .editorconfig
> +root = true
Should this file be present in the repo?

2017-04-17 14:07 UTC, haikuginger commented on tests/unit/test_skytap.py
> -
Let's keep the line break that was removed from here.

2017-04-17 14:07 UTC, haikuginger commented on xblock_skytap/skytap.py
> +            self.raise_error('The Skytap launch service returned a malformed response.', exception=True)
In general, I think we need to tag these error messages for i18n.

2017-04-17 14:36 UTC, bdero commented on xblock_skytap/skytap.py
> +            self.raise_error('The Skytap launch service returned a malformed response.', exception=True)
Ah, took me a second to find [an example](https://github.com/open-craft/xblock-leaderboard/blob/master/leaderboards/leaderboard.py#L34-L36), but I got this added in. Thanks!

2017-04-17 14:36 UTC, bdero commented on tests/unit/test_skytap.py
> -
Ok, added it back in.

2017-04-17 14:36 UTC, bdero commented on .editorconfig
> +root = true
Yup!

2017-04-17 14:59 UTC, bdero commented
@haikuginger Thanks for the review, all comments addressed!

2017-04-17 15:01 UTC, haikuginger approved these changes
:+1:

- [x] I tested this: Ran through the testing script and verified that the outputs were as expected based on the given inputs.
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation

2017-04-17 15:06 UTC, merged